### ISSUE TITLE
`usePgpKeyHex` and `pgpSigningKey` assume 64 bits, breaking `useGpg`

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-pgp#125]
I basically can't sign anything with `usgeGpg := true` that's not the default key. I think the issue is here:

https://github.com/sbt/sbt-pgp/blob/362db608157e066125b850127da6babbae08482b/pgp-plugin/src/main/scala/com/typesafe/sbt/SbtPgp.scala#L34

the `.longValue` call truncates the key, resulting in:

    [error] gpg: secret key "0x5ce4d054c310a1b" not found: Invalid user ID
    [error] gpg: (check argument of option '--default-key')
    [error] gpg: using "678020C06FA1426D3BF6D5AB05CE4D054C310A1B" as default secret key for signing

**Comment by metasim** [comment]
Something spooky is also going on with the non-GPG mode:

### `build.sbt`
```scala
useGpg := false
usePgpKeyHex("86FA449A8DFDD76DD1139FD7011A24C5235119E4")
```

### Output

```bash
[error] java.lang.RuntimeException: Could not find secret key: 79416372552079844
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at com.jsuereth.pgp.SecretKeyRing.$anonfun$apply$1(SecretKeyRing.scala:28)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at com.jsuereth.pgp.SecretKeyRing.apply(SecretKeyRing.scala:28)
[error] 	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.$anonfun$sign$3(PgpSigner.scala:41)
[error] 	at com.typesafe.sbt.pgp.Cache.withValue(SbtHelpers.scala:38)
[error] 	at com.typesafe.sbt.pgp.Cache.withValue$(SbtHelpers.scala:36)
[error] 	at com.typesafe.sbt.pgp.PasswordCache$.withValue(SbtHelpers.scala:55)
[error] 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.$anonfun$withPassphrase$1(SbtPgpCommandContext.scala:41)
[error] 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.retry(SbtPgpCommandContext.scala:49)
[error] 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.withPassphrase(SbtPgpCommandContext.scala:38)
[error] 	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.sign(PgpSigner.scala:37)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:157)
```

**Comment by metasim** [comment]
For reference:

```scala
scala> new BigInteger("678020C06FA1426D3BF6D5AB05CE4D054C310A1B", 16)
res0: java.math.BigInteger = 590883397856013270526019412840333468393184234011
scala> new BigInteger("86FA449A8DFDD76DD1139FD7011A24C5235119E4", 16)
res1: java.math.BigInteger = 770585925817694185483443593076990123428608547300
// For comparison
scala> new BigInteger(Long.MaxValue.toString)
res3: java.math.BigInteger = 9223372036854775807
```

**Comment by eed3si9n** [comment]
In https://github.com/sbt/sbt-pgp/pull/164/commits/5bb23f217001bb0fabc3e8274b8bc11356fc7848, I switched to using String instead of Long, so this should be fixed.
