### ISSUE TITLE
sbt +release fails with GPG error

### ISSUE THREAD

**Issue by pathikrit** [sbt/sbt-pgp#154]
List keys:
```shell
> gpg --list-keys pathikritbhowmick@msn.com

pub   rsa2048 2015-10-15 [SC]
      5E82257FC5B09620C1295D91D8B275D23E219504
uid           [ unknown] Pathikrit Bhowmick <pathikritbhowmick@msn.com>
sub   rsa2048 2015-10-15 [E]

pub   rsa2048 2018-07-24 [SC] [expires: 2020-07-23]
      F5003E5C4718B1F466B244F766AA02EC8AA60DB9
uid           [ unknown] Pathikrit Bhowmick <pathikritbhowmick@msn.com>
sub   rsa2048 2018-07-24 [E] [expires: 2020-07-23]
```

Send keys:
```
gpg --keyserver hkp://pool.sks-keyservers.net --send-keys F5003E5C4718B1F466B244F766AA02EC8AA60DB9
gpg: sending key 66AA02EC8AA60DB9 to hkp://pool.sks-keyservers.net
```

[My build.sbt](https://github.com/pathikrit/better-files/blob/800d63d31582b4119074e0593d257992c1b3cbee/build.sbt)

```
> sbt release

....
....
[error] gpg: Warning: not using '0x66aa02ec8aa60db9' as default key: No secret key
[error] gpg: all values passed to '--default-key' ignored
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.1.pom.asc /Users/pathikrit/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.1.pom'.  Exit code: 2
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:28)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:158)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:155)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / signedArtifacts) Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.1.pom.asc /Users/pathikrit/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.1.pom'.  Exit code: 2
[error] Total time: 8 s, completed Feb 24, 2019 12:22:47 PM
```

What am I doing wrong?

**Comment by joesan** [comment]
Did you get this fixed? I'm running into the same error!

**Comment by coreyauger** [comment]
I see this error as well :(

**Comment by djspiewak** [comment]
I wish I could help more precisely. It's really hard to sort out exactly what's happening in some of these cases. This plugin uses an older set of configuration flags with the `gpg` command, due to the need to maintain compatibility with some other features and generally with Bouncycastle. My first recommendation would be to try [sbt-gpg](https://github.com/jodersky/sbt-gpg), which generally deals with these kinds of cases more smoothly. If you're sticking with sbt-pgp, then I would start by putting the full hash of the key in the build configuration, rather than relying on the abbreviation.

**Comment by coreyauger** [comment]
I will try sbt-gpg.  Thanks!

**Comment by pathikrit** [comment]
This issue is still happening: https://github.com/pathikrit/better-files/pull/319#issuecomment-501240650

What am I doing wrong?

**Comment by pathikrit** [comment]
Ok @eed3si9n helped me in person to resolve this. I was missing the private key on a new computer (I had only imported the public key). I updated the documentation [here](https://stackoverflow.com/users/471136/pathikrit?tab=questions&sort=newest) to handle this and how to check for this.
