### ISSUE TITLE
Publishing fails with invalid packet error

### ISSUE THREAD

**Issue by joesan** [sbt/sbt-pgp#157]
I followed the instructions on this page to configure sbt to use gpg keys and publish to Nexus:

http://caryrobbins.com/dev/sbt-publishing/ and

https://www.scala-sbt.org/release/docs/Using-Sonatype.html

When I ran 

> sbt publishSigned

, I get the following error:

```
[error] gpg: [don't know]: invalid packet (ctb=2d)
[error] gpg: keydb_search failed: Invalid packet
[error] gpg: no default secret key: Invalid packet
[error] gpg: signing failed: Invalid packet
[error] java.lang.RuntimeException: Failure running gpg --detach-sign.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:27)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:157)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:154)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (signedArtifacts) Failure running gpg --detach-sign.  Exit code: 2
[error] Total time: 1 s, completed Apr 25, 2019 9:49:15 AM
```

How could I fix this? I'm using the following sbt version and gpg versions on my Mac:

> sbt: sbt-1.2.8
> gpg: gpg (GnuPG) 2.2.15

**Comment by joesan** [comment]
I followed the instructions from a similiar issue: https://github.com/sbt/sbt-pgp/issues/138

I now face another set of errors as below:

```
[info] Wrote /Users/joesan/Projects/Private/scala-projects/csv-parser/target/scala-2.12/csv-parser_2.12-0.1.2.pom
[error] gpg: signing failed: Timeout
[error] gpg: signing failed: Timeout
[error] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /Users/joesan/.gnupg/pubring.kbx --detach-sign --armor --output /Users/joesan/Projects/Private/scala-projects/csv-parser/target/scala-2.12/csv-parser_2.12-0.1.2.pom.asc /Users/joesan/Projects/Private/scala-projects/csv-parser/target/scala-2.12/csv-parser_2.12-0.1.2.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:28)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:158)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:155)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (signedArtifacts) Failure running 'gpg --no-default-keyring --keyring /Users/joesan/.gnupg/pubring.kbx --detach-sign --armor --output /Users/joesan/Projects/Private/scala-projects/csv-parser/target/scala-2.12/csv-parser_2.12-0.1.2.pom.asc /Users/joesan/Projects/Private/scala-projects/csv-parser/target/scala-2.12/csv-parser_2.12-0.1.2.pom'.  Exit code: 2
```

**Comment by joesan** [comment]
The issue is resolved! It was asking for the password to sign the publish, but I was inactive and hence it timed out! It works now! So closing this issue!
