### ISSUE TITLE
publishSigned fails after upgrade to 2.0.0-M2

### ISSUE THREAD

**Issue by matterche** [sbt/sbt-pgp#158]
After upgrading from 1.1.2 to 2.0.0-M2 `publishSigned` fails with

```
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /Users/me/.gnupg/pubring.gpg --detach-sign --armor --use-agent --output /Users/me/dev/markscheider/target/scala-2.12/markscheider_2.12-2.7.1-SNAPSHOT.pom.asc /Users/merche/dev/markscheider/target/scala-2.12/markscheider_2.12-2.7.1-SNAPSHOT.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:28)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:179)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:176)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (signedArtifacts) Failure running 'gpg --no-default-keyring --keyring /Users/me/.gnupg/pubring.gpg --detach-sign --armor --use-agent --output /Users/me/dev/markscheider/target/scala-2.12/markscheider_2.12-2.7.1-SNAPSHOT.pom.asc /Users/me/dev/markscheider/target/scala-2.12/markscheider_2.12-2.7.1-SNAPSHOT.pom'.  Exit code: 2
```
Reverting back to 1.1.2 fixes the issue.

gpg version is 2.2.13 on MacOS

**Comment by thesamet** [comment]
Same issue on Ubuntu 19.04. `gpg (GnuPG) 2.2.12`

**Comment by eed3si9n** [comment]
You might have to import your key pair - https://github.com/sbt/sbt-pgp#importing-key-pair

**Comment by thesamet** [comment]
Closing the loop: it turned out my key had expired. The earlier version didn't mind.

**Comment by dwijnand** [comment]
https://unix.stackexchange.com/a/177310/37284 for how to extend the expiry date of a key.
