### ISSUE TITLE
NoSuchMethodError : sbt-pgp's BouncyCastle version conflicts with sbt-native-packager's one

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt-pgp#63]
It is currently not possible to use both the latest version of sbt-pgp and the latest version(s) of sbt-native-packager in the same project.
This is caused by a conflict in BouncyCastle versions :

* sbt-pgp uses BouncyCastle 1.49
* sbt-native-packager 0.7/0.8 uses jdeb, which pulls BouncyCastle 1.51.

Obviously, SBT will pick up the latest version.
Unfortunately, [A lot of methods have been removed or deprecated in BouncyCastle 1.51](http://upstream-tracker.org/java/compat_reports/bcpg/1.50_to_1.51/src_compat_report.html), and sbt-pgp happens to use one of them, which leads to the following stacktrace : 

```
java.lang.NoSuchMethodError: org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Ljava/io/InputStream;)V
	at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:55)
	at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:51)
	at com.jsuereth.pgp.StreamingLoadable$class.loadFromFile(StreamingLoadable.scala:11)
	at com.jsuereth.pgp.SecretKeyRing$.loadFromFile(SecretKeyRing.scala:51)
	at com.jsuereth.pgp.PGP$.loadSecretKeyRing(package.scala:38)
	at com.jsuereth.pgp.cli.PgpStaticContext$class.secretKeyRing(context.scala:31)
	at com.typesafe.sbt.pgp.SbtPgpStaticContext.secretKeyRing(SbtPgpCommandContext.scala:8)
	at com.jsuereth.pgp.cli.DelegatingPgpStaticContext$class.secretKeyRing(context.scala:38)
	at com.typesafe.sbt.pgp.SbtPgpCommandContext.secretKeyRing(SbtPgpCommandContext.scala:13)
	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner$$anonfun$sign$1.apply(PgpSigner.scala:42)
	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner$$anonfun$sign$1.apply(PgpSigner.scala:37)
	at com.typesafe.sbt.pgp.Cache$class.withValue(SbtHelpers.scala:38)
	at com.typesafe.sbt.pgp.PasswordCache$.withValue(SbtHelpers.scala:55)
	at com.typesafe.sbt.pgp.SbtPgpCommandContext$$anonfun$1.apply(SbtPgpCommandContext.scala:34)
	at com.typesafe.sbt.pgp.SbtPgpCommandContext.retry(SbtPgpCommandContext.scala:42)
	at com.typesafe.sbt.pgp.SbtPgpCommandContext.withPassphrase(SbtPgpCommandContext.scala:31)
	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.sign(PgpSigner.scala:37)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1$$anonfun$apply$1.apply(PgpSettings.scala:120)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1$$anonfun$apply$1.apply(PgpSettings.scala:117)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:130)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1.apply(PgpSettings.scala:117)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1.apply(PgpSettings.scala:115)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Sidenote : this does not always happens when using both sbt-pgp and sbt-native-packager 0.7/0.8.

The problem arised while I was trying to build an automated release tool for Gatling's various projects, and that required that the `pgpPassphrase` was set in the build definition instead of manually input during the publication process.

**Comment by benmccann** [comment]
Sounds like this issue can be closed now
