### ISSUE TITLE
Can't publishLocalSigned on banana-rdf

### ISSUE THREAD

**Issue by betehess** [sbt/sbt-pgp#75]
I can't `publishLocalSigned` with [banana-rdf](https://github.com/w3c/banana-rdf) (changeset e636b06f2cc92bca). I was initially trying to `release` using sbt-release but I hit a similar issue.

```
> show */*:pgpSecretRing
[info] /home/betehess/.gnupg/secring.gpg
> show */*:pgpPublicRing
[info] /home/betehess/.gnupg/pubring.gpg
```

The two files exist:

```
$ ls -l /home/betehess/.gnupg/secring.gpg /home/betehess/.gnupg/pubring.gpg
-rw------- 1 betehess betehess 3888 Feb 21 14:33 /home/betehess/.gnupg/pubring.gpg
-rw------- 1 betehess betehess 2580 Jan 23 17:33 /home/betehess/.gnupg/secring.gpg
```

I can check that my passphrase is ok:

```
$ echo "1234" | gpg --no-use-agent -o /dev/null --local-user 'Alexandre Bertails <alexandre@bertails.org>' --no-greeting -as - && echo "The correct passphrase was entered for this key"

You need a passphrase to unlock the secret key for
user: "Alexandre Bertails <alexandre@bertails.org>"
2048-bit RSA key, ID 783C0995, created 2015-01-23

The correct passphrase was entered for this key
```

Then when I `publishLocalSigned` I get 

```
[trace] Stack trace suppressed: run last banana/*:signedArtifacts for the full output.
[trace] Stack trace suppressed: run last examples/*:signedArtifacts for the full output.
[error] (banana/*:signedArtifacts) java.io.FileNotFoundException:  (No such file or directory)
[error] (examples/*:signedArtifacts) java.io.FileNotFoundException:  (No such file or directory)
```

and 

```
> last banana/*:signedArtifacts examples/*:signedArtifacts java.io.FileNotFoundException: (No such file or directory) at java.io.FileInputStream.open(Native Method) at java.io.FileInputStream.<init>(FileInputStream.java:146) at com.jsuereth.pgp.SecretKey.sign(PrivateKey.scala:55)
```

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know.
